export { default as Contact } from './Contact.vue'
export { default as Home } from './Home.vue'
export { default as Projects } from './Projects.vue'
export { default as Experience } from './Experience.vue'
export { default as Skills } from './Skills.vue'
